# Generated by Django 4.1.4 on 2022-12-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='превью')),
            ],
        ),
        migrations.CreateModel(
            name='Crib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='категория')),
            ],
        ),
    ]
