# Generated by Django 4.1.4 on 2022-12-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='crib',
            options={'ordering': ('name',), 'verbose_name': 'шпора', 'verbose_name_plural': 'шпоры'},
        ),
    ]
